# Bin
bin: "workflow/bin"

# Input

data_dir_single_dataset: "data/single_dataset" # Note to self: change when explaining wild cards
metadata_single_dataset: "data/single_dataset/metadata_single_dataset.csv"
expression_single_dataset: "data/single_dataset/filtered_expression_single_dataset.tsv"

data_dir: "data"
metadata_name: "metadata.csv"
expression_name: "filtered_expression.tsv"
visualisation_var: "sample_type"


# Wildcards
dataset: ["dataset1", "dataset2"]


## Results directory:
output_dir: "results/snakemake_results_with_wildcards"